### PR TITLE
Update the version of the second `bandit` hook

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull request updates the `bandit (everything else)` hook to use the latest version of [bandit]. It also includes some cleanup for the explanatory comments for both [bandit] hooks.

## 💭 Motivation and context ##

This hook was not kept in sync with updates to the `bandit (tests tree)` hook and is using an older version of [bandit]. The comments make this configuration consistent with https://github.com/cisagov/skeleton-packer/pull/188 and https://github.com/cisagov/skeleton-python-library/pull/111.

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

[bandit]: https://github.com/PyCQA/bandit

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Please remove the checkbox about adding tests in the PR description.

**Comment by mcdonnnj** [comment]
> Please remove the checkbox about adding tests in the PR description.

> Tests have been added and/**or modified** to cover the changes in this PR.

This PR modifies the `pre-commit` configuration which I would consider part of the testing for this repository. Are we considering linting to be separate/different from testing in this regard? I've always taken "testing" to mean any element of our validation mechanisms.

**Comment by jsf9k** [comment]
> This PR modifies the `pre-commit` configuration which I would consider part of the testing for this repository. Are we considering linting to be separate/different from testing in this regard? I've always taken "testing" to mean any element of our validation mechanisms.

Yes, but you're not adding tests that "cover the changes in this PR".  That's what I think that checkbox is for.

If you disagree just leave it, and you can try to convince me later.  I don't want to hold up the train for what is a flea-sized point.

**Comment by jsf9k** [comment]
Feel free to merge this without a second review, since @dav3r is out of the office right now.

**Pull request merged**
