### PR TITLE
Install cisagov/skeleton-python-library directly with `pip`

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull request updates the installation of [cisagov/skeleton-python-library] to be installed directly with `pip`.

> [!NOTE]
> I am creating this pull request against a branch that will represent a larger body of work. This branch will later have a pull request against `develop` once the body of work is completed.

> [!WARNING]
> This change breaks the Docker composition's ability to change the secret message that is printed. I am hoping to restore this functionality by changing part of how [cisagov/skeleton-python-library] works in the future.

## 💭 Motivation and context ##

There is no reason we shouldn't let `pip` handle the retrieval, decompression, and installation of a source package on its own. This is a cleaner approach and involves fewer dependencies in the generated Docker image which in turn gives us a smaller image (130MiB vs. 223MiB).

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

[cisagov/skeleton-python-library]: https://github.com/cisagov/skeleton-python-library

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Comment by dav3r** [comment]
@mcdonnnj Did you mean to enable auto-merge on this skeleton PR?

**Comment by dav3r** [comment]
> @mcdonnnj Did you mean to enable auto-merge on this skeleton PR?

Ah, my bad - I see that this PR is not to the `develop` branch.

**Review by dav3r — APPROVED** [review]
👍 👍

**Comment by mcdonnnj** [comment]
> > @mcdonnnj Did you mean to enable auto-merge on this skeleton PR?
> 
> Ah, my bad - I see that this PR is not to the `develop` branch.

Ah, sorry I forgot to include the blurb about branches that I put in #187 🤦

**Pull request merged**
