### PR TITLE
Improvement/lgtm

### PR DESCRIPTION
**Pull request by felddy**
Add lgtm configuration so that it can find our `requirements-test.txt` file.    Then add the associated shields.

### CODE REVIEW

**Comment by dav3r** [comment]
LGTM! 👓

**Review by jsf9k — APPROVED** [review]
LGTM-related changes LGTM.

**Comment by felddy** [comment]
@dav3r if it LSGTY then give me some approval!

**Review by dav3r — APPROVED** [review]
Sorry, must've hit the wrong button before! 👴

**Pull request merged**
