### PR TITLE
Use Python 3.9 instead of 3.8

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request fixes one place where we are using Python 3.8 but should be using 3.9.

## 💭 Motivation and Context

New and shiny!

## 🧪 Testing

All pre-commit hooks pass.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by felddy — APPROVED** [review]
I've got a 🥵 , and the only prescription is more 🐮 🔔 !

**Review by mcdonnnj — APPROVED** [review]
Thanks for catching this oversight. 🔎🦅

While we're here do we want to fix:
https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L21-L24
and the subsequent uses at:
https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L31
https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L36
https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L40
https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L47
https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L49

**Comment by jsf9k** [comment]
> While we're here do we want to fix:
> https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L21-L24
> 
> 
> and the subsequent uses at:
> https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L31
> 
> 
> https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L36
> 
> 
> https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L40
> 
> 
> https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L47
> 
> 
> https://github.com/cisagov/skeleton-docker/blob/0b979a796b02266599391c9a2ffe121af93b0754/.github/workflows/release.yml#L49

Yes!  Good eye!  Fixed in commit 7d59f7e.

**Review by dav3r — APPROVED** [review]
Cool cool cool. 🍨

**Review by mcdonnnj — APPROVED** [review]
Nice, real nice.

**Pull request merged**
